function [bias_input_gate,...
    bias_forget_gate,...
    bias_output_gate,...
    weight_input_x,...
    weight_input_h,...
    weight_inputgate_x,...
    weight_inputgate_c,...
    weight_forgetgate_x,...
    weight_forgetgate_c,...
    weight_outputgate_x,...
    weight_outputgate_c,...
    weight_preh_h,...
    h_state] = generate_weight(cell_num,input_num,output_num,data_num)

% 网络中门的偏�?
bias_input_gate=rand(1,cell_num);
bias_forget_gate=rand(1,cell_num);
bias_output_gate=rand(1,cell_num);

% 网络权重初始�?
ab=20;
weight_input_x=rand(input_num,cell_num)/ab;
weight_input_h=rand(output_num,cell_num)/ab;
weight_inputgate_x=rand(input_num,cell_num)/ab;
weight_inputgate_c=rand(cell_num,cell_num)/ab;
weight_forgetgate_x=rand(input_num,cell_num)/ab;
weight_forgetgate_c=rand(cell_num,cell_num)/ab;
weight_outputgate_x=rand(input_num,cell_num)/ab;
weight_outputgate_c=rand(cell_num,cell_num)/ab;

% hidden_output权重
weight_preh_h=rand(cell_num,output_num);
h_state=rand(output_num,data_num);
end