function [bias_input_gate,...
    bias_forget_gate,...
    bias_output_gate,...
    weight_input_x,...
    weight_input_h,...
    weight_inputgate_x,...
    weight_inputgate_c,...
    weight_forgetgate_x,...
    weight_forgetgate_c,...
    weight_outputgate_x,...
    weight_outputgate_c,...
    weight_preh_h,...
    h_state,cell_state] = load_weight2(filename)

load(filename);
 
bias_input_gate = final_bias_input_gate;
bias_forget_gate = final_bias_forget_gate;
bias_output_gate = final_bias_output_gate;

weight_input_x=final_weight_input_x;
weight_input_h=final_weight_input_h;
weight_inputgate_x=final_weight_inputgate_x;
weight_inputgate_c=final_weight_inputgate_c;
weight_forgetgate_x=final_weight_forgetgate_x;
weight_forgetgate_c=final_weight_forgetgate_c;
weight_outputgate_x=final_weight_outputgate_x;
weight_outputgate_c=final_weight_outputgate_c;

weight_preh_h = final_weight_preh_h;

h_state = final_h_state;
cell_state = final_cell_state;